apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logspout
  namespace: kube-system
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: logspout
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - resources:
          limits:
            memory: 64Mi
        securityContext:
          privileged: true
        env:
        - name: SYSLOG_TAG
          value: '{{ index .Container.Config.Labels "io.kubernetes.pod.name" }}'
        - name: SYSLOG_HOSTNAME
          value: '{{ index .Container.Config.Labels "io.kubernetes.pod.namespace" }}.{{ index .Container.Config.Labels "io.kubernetes.container.name" }}'
        - name: SYSLOG_FORMAT
          value: rfc3164
        - name: ROUTE_URIS
          valueFrom:
            secretKeyRef:
              name: logspout-secret
              key: route-uri
        image: gliderlabs/logspout:v3.2.3
        name: logspout
        volumeMounts:
        - name: log
          mountPath: /var/run/docker.sock
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: log
        hostPath:
          path: /var/run/docker.sock
      - name: tz-config
        hostPath:
           path: /usr/share/zoneinfo/Asia/Tokyo
